Issue 15.9 9 stable
NishantUpadhyay-BTC/code_forest pull request #16
Opened 2016-09-20 13:39 UTC by ManojParmar-BTC

2016-09-20 13:51 UTC, NishantUpadhyay-BTC commented on app/controllers/users_controller.rb
> +    pocs = pocs.sort_by { |repo| repo.send(params[:column]).count }.reverse
Duplicate Code. Please refactor it and move it to separate method

2016-09-20 14:00 UTC, AmitPatel-BoTreeConsulting commented on app/controllers/users_controller.rb
> +    respond_to do |format|
we can drop this block. It will automatically handled.

2016-09-20 14:00 UTC, AmitPatel-BoTreeConsulting commented on app/controllers/users_controller.rb
> +    params[:poc_sorting] == "ASC" ?
Use if else pair over ternary operator for long expressions.

2016-09-20 14:03 UTC, AmitPatel-BoTreeConsulting commented on app/helpers/users_helper.rb
> +    sorting_order = (params[:column] == column) ? toggle_order(params["#{table}_sorting"]) : "ASC"
Can we make reusable code for pagination and sorting? As mentioned earlier, talk with Bharat/Gautam.

2016-09-20 14:04 UTC, AmitPatel-BoTreeConsulting commented on app/views/users/_repository_table.html.erb
> +    <% @repositories.each do |repo| %>
As commented before use each_with_inedex

2016-09-20 14:05 UTC, amitpatelx requested changes

2016-09-20 14:05 UTC, amitpatelx commented on app/controllers/application_controller.rb
> +    repositories.select{ |repo| !poc_names.include?(repo[:name]) }
Filter this using above query only. How about adding another `where` ?

2016-09-20 14:05 UTC, amitpatelx commented on app/controllers/users_controller.rb
> +    @pocs = ['impressions', 'favourites'].include?(params[:column]) ?
Literal array is candidate for constant. Otherwise, it will created on each request.

Also Use if else pair instead of ternary operator for multiline instructions. Read and adopt https://github.com/bbatsov/ruby-style-guide

2016-09-22 05:03 UTC, ManojParmar-BTC commented on app/controllers/application_controller.rb
> +    repositories.select{ |repo| !poc_names.include?(repo[:name]) }
here 'repositories' is an array so i cant use where.

2016-09-23 05:28 UTC, merged